server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: promtail-webapp
    static_configs:
      - targets:
        - localhost
        labels:
          job: springboot-app
          __path__: /var/log/springboot/simplewebapp.log


