global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'simplewebapp'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['simplewebapp:8081']
        labels:
          group: 'backend'