version: '3.8'

services:
  simplewebapp:
    image: simplewebapp
    build:
      context: ./simplewebapp/simplewebapp/.
    ports:
      - "8081:8081"
    volumes:
      - ./logs:/app/logs
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - simplewebapp
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - grafana
    networks:
      - monitoring


  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./logs:/var/log/springboot
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - grafana
    networks:
      - monitoring


volumes:
  grafana-storage:

networks:
  monitoring: